after_success: 
  - "npm run coverage"
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
- npm install
services:
- postgresql
env:
  global:
    - NODE_ENV=development
    - SECRET_KEY = secretKey
    - PG_USER = kimenyi
    - PG_HOST = localhost
    - PG_URL=postgresql://kimenyi:kigali@localhost/FreeMentor 
    - PG_DATABASE = FreeMentor
    - PG_PASSWORD = kigali
    - PG_PORT = 5432
before_script:
- psql -c 'CREATE DATABASE FreeMentor;' -U postgres
- psql -c "CREATE USER kimenyi WITH PASSWORD 'kigali';" -U postgres
notifications: 
  email: false
script: 
  - "npm run test"
after_success: npm run coverage
sudo: false

